sudo: required
services:
  - docker

before_install:
  - docker build -t svarpe/react-test -f ./client/Dockerfile.dev ./client ## we can only use the dev for test 

script:
  - docker run svarpe/react-test npm test -- --coverage

after_success:
  - docker build -t svarpe/multi-client-sv ./client
  - docker build -t svarpe/multi-nginx-sv ./nginx
  - docker build -t svarpe/multi-server-sv ./server
  - docker build -t svarpe/multi-worker-sv ./worker

 # login to the Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 # take those images and push them to the docker hub
  - docker push svarpe/multi-client-sv
  - docker push svarpe/multi-nginx-sv
  - docker push svarpe/multi-server-sv
  - docker push svarpe/multi-worker-sv