sudo: required
services:
  - docker

before_install:
  - docker build -t svarpe/react-test -f ./client/Dockerfile.dev ./client ## we can only use the dev for test 

script:
  - docker run -e CI=true svarpe/react-test npm test

after_success:
  - docker build -t svarpe/multi-client ./client
  - docker build -t svarpe/multi-nginx ./nginx
  - docker build -t svarpe/multi-server ./server
  - docker build -t svarpe/multi-worker ./worker

 # login to the Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 # take those images and push them to the docker hub under public repository
 #travis needs to be configured with docker ID and password so that images get pushed to docker hub
  - docker push svarpe/multi-client
  - docker push svarpe/multi-nginx
  - docker push svarpe/multi-server
  - docker push svarpe/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultidockerEnv-env
  bucket_name: elasticbeanstalk-us-east-1-756575261520
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
